name: Build and Publish Package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@${{ github.repository_owner }}'

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Build TypeScript
        run: pnpm build

      - name: Disable git hooks
        run: git config --local core.hooksPath /dev/null

      - name: Run Semantic Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set package version and update package metadata
        run: |
          pnpm pkg set name=@${{ github.repository_owner }}/cmdr-cli
          pnpm pkg set publishConfig.registry=https://npm.pkg.github.com
          pnpm pkg set repository.type=git
          pnpm pkg set repository.url=git+https://github.com/${{ github.repository_owner }}/cmdr-cli.git

      - name: Publish to GitHub Package Registry
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
